### ISSUE TITLE
{jpmn-primary-definition-render-error} and {jpmn-extra-definitions-render-error} when creating a simple Anki Card

### ISSUE THREAD

**Issue by Sfoyarbide** [Aquafina-water-bottle/jp-mining-note#18]
**Describe the bug**
Hi I been following the documentation to install Jp-mining-note until I had an error in the section for setup Yomichan (now using yomitan). Basicily put if I try to create a new card, it's says in the pop-up window of yomitan:

"2 errors occurred:
Template render error for {jpmn-primary-definition}
Template render error for {jpmn-extra-definitions}"

I copy and paste several times the template describe just as it should be in the documention; but it just does not work.

**To Reproduce**
1. Click on the add button of the Yomitan pop-up.
2. It creates the card but it has the following error statement inside the pop-up and the Anki field.
3. "2 errors occurred: Template render error for {jpmn-primary-definition} Template render error for {jpmn-extra-definitions}"

**Expected behavior**
I should have my bilingual definition in field of primary definition and in the extra definitions field I should have my monolingual definition. 

**Example Cards(s)**
[jpmn-primary-definition-render-error_jpmn-extra-definitions-render-error.txt](https://github.com/Aquafina-water-bottle/jp-mining-note/files/13653885/jpmn-primary-definition-render-error_jpmn-extra-definitions-render-error.txt)

**Screenshots**
Example 1:
![image](https://github.com/Aquafina-water-bottle/jp-mining-note/assets/63980929/e6a85fb4-41a6-48ff-a9d0-2ffdcffafb85)

Example 2:
![image](https://github.com/Aquafina-water-bottle/jp-mining-note/assets/63980929/08897742-411c-433b-9be2-66666099ffb8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Anki version: ⁨23.10.1 Qt 6.6.0 PyQt 6.6.0
 - jp-mining-note version: 0.11.0.4

**Additional context**
I'd try with my knowledge all possible solutions but at this point I think is just a weird bug, that only happend to me.

**Comment by WaddlesPlays** [comment]
Same issue, on Yomitan for Firefox and latest prerelease of JPMN. This also applies to {jpmn-secondary-definition}, at least for me.
I tried the last stable of Yomichan with the same setup as my Yomitan install and I could not reproduce this issue, so using Yomichan for now is a fine workaround if you don't mind reimporting your dictionaries.

**Comment by jrbarona4** [comment]
Try using [Yomibaba](https://github.com/forsakeninfinity/yomibaba), it's a temporary fork for Yomichan.

**Comment by Sfoyarbide** [comment]
Yomibaba, works perfect with JP Mining Note. I shall consider Yomibaba the most stable fork. 
Much appreciated!
