### ISSUE TITLE
Keep getting (新和英) as primary definition for all cards

### ISSUE THREAD

**Issue by ansoniikun** [Aquafina-water-bottle/jp-mining-note#19]
As the title says, all the cards' primary definition default are set to the phrase above. I noticed this is just a definition heading for one of the dictionaries I currently have installed to Yomitan. not sure if this is a jpmn note issue or a yomitan issue, would appreciate any help. Of course I can just overwrite the definition by setting `opt-selection-text-dictionary to true` but I prefer to use the first definition by default. All other definitions are off as well for secondary definition I get `⭐Jitendex [2023-12-12]`

**Comment by Vadyy** [comment]
I have the same exact issue! Have you figured it out?

**Comment by Vadyy** [comment]
I figured it out, you need to update the handlebars template. Reset it first though.
Get them from here: (version 1.0.5)
https://arbyste.github.io/jp-mining-note/setupyomichan/

![image](https://github.com/user-attachments/assets/4c4c2ced-607b-4d33-9024-568f8ceb2f8f)
